version: "3.8"

services:
  gosensor-collector:
    image: gosensor-collector:latest
    ports:
      - "${API_PORT:-4001}:4001"
      - "${GRPC_PORT:-50051}:50051"
    environment:
      - API_PORT=${API_PORT:-4001}
      - GRPC_PORT=${GRPC_PORT:-50051}
    networks:
      - gosensor_network
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  gosensor_network:
    external: true
    name: gosensor_network
    driver: overlay
    attachable: true
